name: Upload Docker image to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > /tmp/gcp_key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
          gcloud auth configure-docker

      - name: Build Docker image (fail on errors)
        run: |
          set -e
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name:${{ github.ref }} .

      - name: Push Docker image to Artifact Registry
        run: |
          set -e
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name:${{ github.ref }}
